### ISSUE TITLE
TCF v1 vs v2

### ISSUE THREAD

**Issue by matthieujoossen** [prebid/go-gdpr#16]
Hi,

I want to know if you have a due date for TCF v2 support and if you are expected to support both during transition period?

In my case I can receive v1 and v2 in the same time and I want accept the both until TCF v1 is authorized.

Thanks,

Matthieu

**Comment by SyntaxNode** [comment]
Closing this older ticket. TCF2 support is released. We're discussing plans to remove TCF1 support from this library.
