### ISSUE TITLE
How to access PurposeLITransparency

### ISSUE THREAD

**Issue by vikasreddyncs** [prebid/go-gdpr#26]
Hi, 
I would like to check the purpose satisfied PurposeLITransparency, but the interface does not have that. Could you please help me to access that fields

**Comment by hhhjort** [comment]
The general API does not give that, as LI did not exist in TCF v1. If you have a `vendorconsent.tcf2.ConsentMetadata` object, you can call the PurposeLITransparency() method on it. To get the tcf2 object, you can do a type assertion on the generic interface to verify that it is tcf2, and get the underlying `ConsentMetadata` object.

**Comment by mansinahar** [comment]
@vikasreddyncs Did that answer your question? Can we close this out?

**Comment by mansinahar** [comment]
Closing this out due to inactivity. Please reopen if you still have any questions.
