### ISSUE TITLE
Return a concrete type from vendorconsent/tcf2 Parse functions

### ISSUE THREAD

**Issue by joewreschnig** [prebid/go-gdpr#31]
Hi,

I would prefer if the `Parse` and `ParseString` functions specific to TCF2 returned a `ConsentMetadata` rather than a boxed `api.VendorConsents`. This would allow easier access to e.g. the `PurposeLITransparency` method, and follow the general Go idiom of interfaces for arguments, structs for returns. Unfortunately I don't see how to do this in a compatible way, so I would like to discuss a) is this possible despite some breakage? and b) which kind of breakage is preferred?

The reason it doesn't seem possible is that `ConsentMetadata` is returned as, and boxed as, as a non-pointer type. So a `Parse(data []byte) (ConsentMetadata, error)` would have to return a an empty, invalid `ConsentMetadata` and break the code of anyone checking `!= nil`, but updating the methods and using `Parse(data []byte) (*ConsentMetadata, error)`would change the type that gets boxed by the version-agnostic `Parse`.

Personally I think `Parse(data []byte) (*ConsentMetadata, error)` and using pointer receivers is the better API, but also seems like the breakage more likely to cause runtime errors. (Both cause runtime issues if someone stored the return to an explicit `api.VendorConsents`, re-boxing it, but the pointer return also affects code that assumes it knows the exact type of a v2 consent boxed by the version-agnostic `Parse`.)

**Comment by bsardo** [comment]
Hi @joewreschnig ,

Thank you for your inquiry and suggested improvements. The idea of returning a concrete type from a TCF2-specific method is an idea worth considering. However after further review with the team, we don’t think introducing a breaking change for a small subjective API improvement is a tradeoff worth making at this time. Perhaps this is something we eventually revisit when we remove TCF1, which is no longer supported. That seems like a good time to reevaluate the overall design.

**Comment by joewreschnig** [comment]
I disagree the improvement is subjective; it has a runtime cost and requires noisy casting to use fundamental TCF2 features (#26). But, I understand that even objective improvements need to be balanced against (also objective) compatibility concerns.
